<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Prospect;
use Doctrine\ORM\OptimisticLockException;
use Doctrine\ORM\ORMInvalidArgumentException;

/**
 * ProspectRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProspectRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param Prospect $entity
     * @return ProspectRepository
     * @throws ORMInvalidArgumentException
     */
    public function persist(Prospect $entity)
    {
        $this->getEntityManager()->persist($entity);
        return $this;
    }

    /**
     * @param null|Prospect|Prospect[] $entity
     * @throws OptimisticLockException
     */
    public function flush($entity = null)
    {
        $this->getEntityManager()->flush($entity);
    }
}
