services:
  app.repository.prospect:
    class: 'AppBundle\Repository\ProspectRepository'
    factory:
      - '@doctrine.orm.default_entity_manager'
      - 'getRepository'
    arguments:
      - 'AppBundle\Entity\Prospect'
  app.controller.prospect:
    class: 'AppBundle\Controller\ProspectController'
    arguments:
      - '@app.repository.prospect'
